version: "3"

services:
  nginx:
    build: docker/nginx
    container_name: "hqe_nginx"
    restart: unless-stopped
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "h-qe.ir"
      LETSENCRYPT_HOST: "h-qe.ir"
      LETSENCRYPT_EMAIL: "admin@hqe.ir"
    volumes:
      - ./:/var/www/:rw
      - ./docker/nginx/sites/:/etc/nginx/conf.d/:ro
      - /mystorage/docker_logs/hqe/logs/nginx:/var/log/nginx:rw
      - /etc/hosts:/etc/hosts:ro
    depends_on:
      - app
    networks:
      public:
      
  #MySQL Service
  db:
    image: mysql:8.0
    container_name: "hqe_db"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - 33070:3306
    volumes:
      #- /mystorage/docker_data/hqe/db_data:/var/lib/mysql
      - /etc/hosts:/etc/hosts:ro
    environment:
      MYSQL_ROOT_PASSWORD: 'MysqlMasterPass@123'
      MYSQL_DATABASE: 'hqe_main'
      MYSQL_USER: 'hqe_user'
      MYSQL_PASSWORD: 'MysqlHananPass@123'
      #SERVICE_TAGS: dev
      #SERVICE_NAME: mysql
    networks:
      public:
      
  app:
    build: docker/php
    depends_on:
      - db
    container_name: "hqe_fpm"
    restart: unless-stopped
    volumes:
      - ./:/var/www/:rw
      - /etc/hosts:/etc/hosts:ro
      - /mystorage/docker_logs/hqe/logs/php-fpm:/var/log/php-fpm
    networks:
      public:

networks:
  public:
    external:
      name: public
